version: 2.1
orbs:
  jwt-creator: isanasan/jwt-creator@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.6

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: 'cimg/go:1.20'
    steps:
      - run:
          name: "create pem file"
          command: echo $test_pem | base64 --decode > ./hoge.pem
      - jwt-creator/create:
          private-key-file: "hoge.pem"
          expires-in-seconds: 500
          issuer: "hogehuga"
      - run:
          name: "echo jwt token"
          command: echo "${JWT_TOKEN}"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          context: test pem
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: isanasan/jwt-creator
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
